---
ID: "2ca1c8d3-3c57-4898-b248-7ba0454da7ff"
Parent: "52866305-bbf8-4b43-aed0-ae0b8e52e7c5"
Template: "52866305-bbf8-4b43-aed0-ae0b8e52e7c5"
Path: /sitecore/templates/Feature/MvpListing/MvpCategory/__Standard Values
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Office/32x32/radio_button_unselected.png
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200924T050230Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a121644f-2796-4fc5-a3f1-82c52f4ee8ed"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20200924T050830Z
    - ID: "ed58042a-36af-4723-9717-1af05cc8b4e9"
      Hint: Name
      Value: $name
